Algoritmo "calculos"

Var
num1, num2, num3, num4, soma, subtracao, multiplicacao :real

Inicio
escreval("Digite o primeiro número")
leia(num1)

escreval("Digite o segundo número")
leia(num2)

soma := num1 + num2

escreval("Digite o terceiro número")
leia(num3)

escreval("Digite o quarto número")
leia(num4)

subtracao := num1 - num2

multiplicacao := soma * subtracao

escreval("O valor final é", multiplicacao)

Fimalgoritmo