Algoritmo "Vetor_Repetição"

Var
nome_filme: vetor[1..5] de caracter
contador: inteiro
Inicio

para contador de 1 ate 5 faca
     escreval("Digite o nome de um filme")
     leia(nome_filme[contador])
     escreval("")
     contador := contador + 1
fimpara

para contador de 1 ate 5 faca
     escreval("O nome do filme da posição", contador ," é ", nome_filme[contador])
     escreval("")
     contador := contador + 1
fimpara

Fimalgoritmo